# Generated by Django 5.2.11 on 2026-02-04 13:26

import django.core.validators
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_time_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='actual_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Temps effectif (jours)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estimated_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Temps prévu (jours)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('evol', 'Évolution'), ('exploit', 'Exploitation')], default='bug', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to=tickets.models.ticket_attachment_upload_to, verbose_name='Fichier'),
        ),
    ]
