# Generated by Django 5.2.11 on 2026-02-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('created', 'Non affecté'), ('assigned', 'Affecté'), ('in_progress', 'En cours'), ('delivered_preprod', 'Livré préprod'), ('delivered_prod', 'Livré prod'), ('validated', 'Validé'), ('cancelled', 'Annulé')], default='created', max_length=30, verbose_name='Statut'),
        ),
    ]
